config/routes.rb
Superlatives::Application.routes.draw do

  root to: 'groups#index'

  resources :groups do
    resources :launchers
  end

  resources :superlatives do
    resources :votes
  end

  resources :users

  get 'welcome', to: 'welcomes#welcome'

  get 'auth/:provider/callback', to:'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/group.rb
class Group < ActiveRecord::Base

  validates_presence_of :name

  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id'

  has_many :superlatives
  has_many :users, through: :memberships
  has_many :memberships
  has_many :launchers

end

app/models/launcher.rb
class Launcher < ActiveRecord::Base
  has_many :launcher_superlatives
  has_many :superlatives, through: :launcher_superlatives
  has_many :votes

  belongs_to :group

  validates_presence_of :name
end

app/models/launcher_superlative.rb
class LauncherSuperlative < ActiveRecord::Base
  belongs_to :launcher
  belongs_to :superlative
end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :group

end

app/models/superlative.rb
class Superlative < ActiveRecord::Base

  validates_presence_of :name

  has_many :launcher_superlatives
  has_many :launchers, through: :launcher_superlatives
  has_many :votes, dependent: :destroy

  belongs_to :group

  def winner
    count_hash = Hash.new(0)
    if votes == []
      "not chosen yet."
    else
      votes.each do |vote|
        count_hash[vote.launcher] += 1
      end
      winner = count_hash.max_by{|k,v| v}.first
        winner.name
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :votes
  has_many :groups, through: :memberships
  has_many :memberships

  def groups_admin_for(current_user_id)
    groups = self.groups.where("admin_id = ?", current_user_id)
  end

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
    end
  end

  def has_vote?(superlative)
    superlative.votes.each do |vote|
      return true if vote.user == self
    end
    return false
  end

  def find_vote(superlative)
    superlative.votes.each do |vote|
      return vote if vote.user == self
    end
    return "vote does not exist"
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :launcher
  belongs_to :superlative

  validates_uniqueness_of :user, scope: :superlative
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    if !current_user
      flash.now[:notice] = "You must authenticate!!"
      redirect_to welcome_path
    end
  end


  helper_method :current_user

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  skip_before_action :authenticate_user
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    if current_user
      @group = Group.new
      @groups = current_user.groups
    end
  end

  def create
    group = Group.new(group_params)
    group.admin = current_user
    if group.save
      current_user.groups << group
      flash[:notice] = "You created a group"
      redirect_to new_group_launcher_path(group)
    else
      flash[:alert] = "Fail"
      redirect_to root_path
    end
  end

  def show

  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/launchers_controller.rb
class LaunchersController < ApplicationController

  def new
    @group = Group.find(params[:group_id])
    @launchers = Launcher.all
    @launcher = Launcher.new
  end

  def index
    @launchers = Launcher.all
    @launcher = Launcher.new
  end

  def create
    group = Group.find(params[:group_id])
    launcher = Launcher.new(launcher_params)
    launcher.group = group
    if launcher.save
      flash[:notice] = "Congrats yo"
      redirect_to new_group_launcher_path(group)
    else
      flash[:error] = "ERRRRR"
      redirect_to new_group_launcher_path(group)
    end
  end

  private

  def launcher_params
    params.require(:launcher).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end


end

app/controllers/superlatives_controller.rb
class SuperlativesController < ApplicationController

  def index
    @superlatives = Superlative.all
    @superlative = Superlative.new
  end

  def create
    @superlative = Superlative.new(superlative_params)
    if @superlative.save
      flash[:success] = "yay, new superlative"
      redirect_to superlatives_path
    else
      flash[:alert] = "No superlative saved"
      redirect_to superlatives_path
    end
  end

  def show
    @superlative = Superlative.find(params[:id])
    @launchers = Launcher.all
    @vote = Vote.new
  end

  private

  def superlative_params
    params.require(:superlative).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def index

  end

  def create
    superlative = Superlative.find(params[:superlative_id])
    launcher = Launcher.find(params[:vote][:launcher])
    @vote = Vote.new
    @vote.superlative = superlative
    @vote.launcher = launcher
    @vote.user = current_user
    if @vote.save
      flash[:success] = "Thanks for voting!"
      redirect_to superlative_path(superlative)
    else
      flash[:alert] = "You can't vote twice!"
      redirect_to superlative_path(superlative)
    end
  end

  def destroy
    vote = Vote.find(params[:id])
    superlative = Superlative.find(params[:superlative_id])
    if vote.destroy
      flash[:sucess] = "Vote destroyed!"
      redirect_to superlative_path(superlative)
    else
      flash[:alert] = "No"
      redirect_to superlative_path(superlative)
    end
  end

  # private
  # def vote_params
  #   params.require(:vote).permit(:launcher, :superlative_id).merge(user: :current_user)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<% unless current_user %>
  <h1>Welcome!  You must sign in via Twitter to vote.</h1>
<% else %>
  <%= simple_form_for @group do |f| %>
    <%= f.text_field :name, placeholder: "Create a group name" %>
    <%= f.button :submit, class: 'button' %>
  <% end %>

  <h3>Groups I Just Belong To:</h3>
  <% current_user.groups.each do |group| %>
    <%= link_to group.name, group_path(group) %>
    <br>
    <br>
  <% end %>

  <h3>Groups I'm an Admin For:</h3>
  <% current_user.groups_admin_for(current_user.id).each do |group| %>
    <%= link_to group.name, group_path(group) %>
    <br>
    <br>
  <% end %>
<% end %>

app/views/groups/show.html.erb
<h3>GROUP NAME: <%=@group.name%></h3>
<h4>Group Count: <%= @group.launchers.count %></h4>

<%= link_to "Back To All Groups", groups_path %>
<br>
<br>

<%= link_to "Add Members", new_group_launcher_path(@group) %>

app/views/launchers/new.html.erb
<h1><%= "ADD MEMBERS TO: #{@group.name}"%></h1>

<h3><%= link_to "Back to Group", group_path(@group) %></h3>

<%= simple_form_for [@group, @launcher] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

<h3><%= @group.launchers.count %></h3>



<% @group.launchers.each do |launcher| %>
  <%= launcher.name %><br><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Superlatives" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <% if current_user %>
    Signed in as <%= current_user.name %><br>
    <%= link_to "Sign out", signout_path %>
  <% end %>


  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "#{name} alert-box" %>
  <% end %>

  <body>

    <%= yield %>

  <% unless current_user %>
    <div class='sign-in'>
      <%= link_to "Sign in with Twitter", "/auth/twitter" %>
    </div>
  <% end %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/superlatives/index.html.erb
<h1>Superlatives</h1>

<%= simple_form_for(@superlative) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>


<% @superlatives.each do |superlative| %>
  <%= link_to superlative.name, superlative_path(superlative) %><br><br>
<% end %>

app/views/superlatives/show.html.erb
<h2><%= @superlative.name %></h2>

<h3>Winner is <%= @superlative.winner %></h3>

<%if current_user.has_vote?(@superlative)%>
  <%= link_to "Destroy Vote", superlative_vote_path(@superlative, current_user.find_vote(@superlative)), method: :delete%>
<%else %>

  <% @launchers.each do |launcher| %>
    <%= launcher.name %>
    <%= simple_form_for [@superlative, @vote] do |f| %>
      <%= f.hidden_field :launcher, value:launcher.id %>
      <%= f.button :submit, "+1" %>
    <% end %>

  <% end %>
<% end%>

app/views/users/index.html.erb
<h1>User Sign in</h1>


<div>
</div>